name: tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: 1
      TERM: xterm-color
      MYPY_FORCE_COLOR: 1
      MYPY_FORCE_TERMINAL_WIDTH: 200
      PYTEST_ADDOPTS: --color=yes

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Pip Install
        run: make install

      - name: Pytest
        run: make test

      - name: Lint
        run: make lint

      - name: Mypy
        run: make mypy

      - name: Refurb
        run: make refurb
